In [1]:
import random
import numpy as np

random python modul and Numpy

In [6]:
n = 10
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]
x[:2], y[:3]

([0.8060840525241353, 0.8203355218897445],
 [0.7825342298052728, 0.9773195416783705, 0.09229614964430433])

random number between 0 & 1
change: 
n=1000000 -> 10
x[:3] ->2

In [23]:
z = [x[i] + y[i] for i in range(n)]
z[:4]
[1.217, 1.061, 1.781]

[1.217, 1.061, 1.781]

In [ ]:
change:
z[:3 -> 4] nothing changed

In [11]:
%timeit [x[i] + y[i] for i in range(n)]


761 ns ± 17.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


takes that long to compute

In [14]:
xa = np.array(x)
ya = np.array(y)
xa[:3]


array([0.80608405, 0.82033552, 0.44980385])

same with NumPy
need to voncert lists to array
xa & ya contain same thing as x & y
arrays should be better than lists

In [20]:
za = xa + ya
za[:5]

array([1.58861828, 1.79765506, 0.5421    , 1.35955272, 0.78842066])

array + array = adding elements of  arrays component by component
change: 
za 3 -> 5
numbers counted increased to the number

In [24]:
%timeit xa + ya

409 ns ± 3.16 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


time faster compared to the previous one

In [25]:
%timeit sum(x)

108 ns ± 0.938 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


pure python;

In [26]:
%timeit np.sum(xa)

3.09 µs ± 53.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


NumPy is faster

In [29]:
d = [abs(x[i] - y[j])
     for i in range(10)
     for j in range(10)]
d[:5]

[0.023549822718862523,
 0.17123548915423525,
 0.713787902879831,
 0.21738280871824622,
 0.6564611510355851]

change:
range 1000 (out of range -> dont function) -> 10 (in range)
d 3 -> 5 - 5 results

In [33]:
da = np.abs(xa[:10, np.newaxis] - ya[:10])
da

array([[0.02354982, 0.17123549, 0.7137879 , 0.21738281, 0.65646115,
        0.63176478, 0.01793202, 0.48942642, 0.01997062, 0.46033584],
       [0.03780129, 0.15698402, 0.72803937, 0.23163428, 0.67071262,
        0.64601625, 0.00368055, 0.50367789, 0.03422209, 0.47458731],
       [0.33273038, 0.52751569, 0.3575077 , 0.1388974 , 0.30018095,
        0.27548458, 0.37421223, 0.13314622, 0.33630958, 0.10405563],
       [0.01168275, 0.20646806, 0.67855533, 0.18215024, 0.62122858,
        0.59653221, 0.0531646 , 0.45419385, 0.01526195, 0.42510327],
       [0.14373647, 0.33852178, 0.54650161, 0.05009652, 0.48917486,
        0.46447849, 0.18521832, 0.32214013, 0.14731567, 0.29304955],
       [0.39899166, 0.59377697, 0.29124642, 0.20515867, 0.23391967,
        0.2092233 , 0.44047351, 0.06688494, 0.40257086, 0.03779436],
       [0.37195616, 0.56674147, 0.31828192, 0.17812317, 0.26095517,
        0.2362588 , 0.413438  , 0.09392044, 0.37553536, 0.06482986],
       [0.15159324, 0.04319207, 0.8418313

change:
from 1000 -> 10 : slight change seen

In [38]:
%timeit [abs(x[i] - y[j]) \
         for i in range(10) \
         for j in range(10)]

8.55 µs ± 76.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [39]:
%timeit np.abs(xa[:1000, np.newaxis] - ya[:1000])

2.92 µs ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


speed difference